apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: Service
    - group: '*'
      kind: Namespace
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: Deployment
    - group: '*'
      kind: Service
    - group: '*'
      kind: Namespace
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: getting-started-preview
spec:
  generators:
    - pullRequest:
        github:
          owner: anmiralles
          repo: quarkus-getting-started
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'getting-started-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: helm/
        repoURL: 'https://github.com/anmiralles/quarkus-getting-started.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{branch}}'
            - name: image.tag
              value: '{{head_sha}}'
            - name: image.name
              value: quarkus-getting-started
            - name: name
              value: getting-started
      syncPolicy:
        automated:
          selfHeal: true