apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicmgtZWUtYW1pcmFsbGUiLCJwYXNzd29yZCI6InA0cjRjM3Q0bTBMLiIsImVtYWlsIjoiYW1pcmFsbGVAcmVkaGF0LmNvbSIsImF1dGgiOiJjbWd0WldVdFlXMXBjbUZzYkdVNmNEUnlOR016ZERSdE1Fd3UifX19
type: kubernetes.io/dockerconfigjson
