apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: development-trigger
  namespace: cicd
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: development-tb
  template:
    ref: development-tt
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: development-tb
  namespace: cicd
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-commit-message
    value: $(body.head_commit.message)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: development-tt
  namespace: cicd
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: main
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-$(tt.params.git-repo-name)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: development-pipeline
      params:
      - name: app-name
        value: $(tt.params.git-repo-name)
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: image
        value: quay.io/rh-ee-amiralle/$(tt.params.git-repo-name)
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: development-pipeline-pvc
      - name: dockerconfig
        secret:
          secretName: quay-reg-secret
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: development-el
  namespace: cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      name: trigger-2
      template:
        ref: development-tt
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-development-route
  namespace: cicd
  labels:
    app.kubernetes.io/instance: cicd-config
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: development-el
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: el-development-el
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None